"""empty message

Revision ID: 0af208211d8f
Revises: bb925431fed5
Create Date: 2018-06-21 14:37:12.994171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af208211d8f'
down_revision = 'bb925431fed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    "BOBBBBB"
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('optom_there', sa.Column('Practice', sa.VARCHAR(length=20), nullable=True))
    op.create_index('ix_optom_there_Practice', 'optom_there', ['Practice'], unique=False)
    op.drop_index(op.f('ix_optom_there_practice'), table_name='optom_there')
    op.drop_column('optom_there', 'practice')
    op.drop_index(op.f('ix_archive_app_user_id'), table_name='archive_app')
    op.drop_index(op.f('ix_archive_app_date_time'), table_name='archive_app')
    op.drop_table('archive_app')
    # ### end Alembic commands ###
