"""empty message

Revision ID: 0f1bc3d57548
Revises: 7027112fd24b
Create Date: 2018-03-31 10:17:17.140282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1bc3d57548'
down_revision = '7027112fd24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_admin'), 'user', ['admin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_admin'), table_name='user')
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
