"""empty message

Revision ID: 0f576399b7fd
Revises: 0f1bc3d57548
Create Date: 2018-04-16 10:35:25.980111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f576399b7fd'
down_revision = '0f1bc3d57548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('need_optom', sa.Boolean(), nullable=True),
    sa.Column('practice', sa.String(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_date_time'), 'appointments', ['date_time'], unique=False)
    op.add_column('user', sa.Column('address1', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('address2', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('app_missed', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('mon_per_appoint', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('perc_app_attend', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('postcode', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('telephone_num', sa.String(length=14), nullable=True))
    op.add_column('user', sa.Column('total_mon_spen', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('total_num_app', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('town_city', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_telephone_num'), 'user', ['telephone_num'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telephone_num'), table_name='user')
    op.drop_column('user', 'town_city')
    op.drop_column('user', 'total_num_app')
    op.drop_column('user', 'total_mon_spen')
    op.drop_column('user', 'telephone_num')
    op.drop_column('user', 'postcode')
    op.drop_column('user', 'perc_app_attend')
    op.drop_column('user', 'mon_per_appoint')
    op.drop_column('user', 'app_missed')
    op.drop_column('user', 'address2')
    op.drop_column('user', 'address1')
    op.drop_index(op.f('ix_appointments_date_time'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
