"""empty message

Revision ID: 1504e866d914
Revises: b6b1e591553c
Create Date: 2018-06-18 10:08:49.831886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1504e866d914'
down_revision = 'b6b1e591553c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optom_there',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('Practice', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optom_there_Practice'), 'optom_there', ['Practice'], unique=False)
    op.drop_index('appointments_date_time_uindex', table_name='appointments')
    op.create_index(op.f('ix_shop_age'), 'shop', ['age'], unique=False)
    op.drop_index('ix_shop_sex', table_name='shop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_shop_sex', 'shop', ['age'], unique=False)
    op.drop_index(op.f('ix_shop_age'), table_name='shop')
    op.create_index('appointments_date_time_uindex', 'appointments', ['date_time'], unique=1)
    op.drop_index(op.f('ix_optom_there_Practice'), table_name='optom_there')
    op.drop_table('optom_there')
    # ### end Alembic commands ###
