"""0000000

Revision ID: 1f81331aa67c
Revises: ece8f293fb04
Create Date: 2018-05-03 00:04:05.284641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f81331aa67c'
down_revision = 'ece8f293fb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    "More indent stuff"
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'shop_id')
    # ### end Alembic commands ###
