"""empty message

Revision ID: 469b5ce9a23e
Revises: 0af208211d8f
Create Date: 2018-07-14 17:03:29.234843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469b5ce9a23e'
down_revision = '0af208211d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    "DONE"
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('quest_ans_id_uindex', 'quest__ans', ['id'], unique=1)
    op.drop_index(op.f('ix_quest__ans_question'), table_name='quest__ans')
    op.drop_index(op.f('ix_quest__ans_answer'), table_name='quest__ans')
    op.alter_column('quest__ans', 'question',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('quest__ans', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('optom_there', sa.Column('Practice', sa.VARCHAR(length=20), nullable=True))
    op.create_index('ix_optom_there_Practice', 'optom_there', ['Practice'], unique=False)
    op.drop_index(op.f('ix_optom_there_practice'), table_name='optom_there')
    op.drop_column('optom_there', 'practice')
    # ### end Alembic commands ###
