"""empty message

Revision ID: 4aacc7417aa7
Revises: a3231da0897b
Create Date: 2018-05-14 09:16:59.698815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aacc7417aa7'
down_revision = 'a3231da0897b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    "bob"
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('date_created', sa.DATETIME(), nullable=True))
    op.drop_column('cart', 'date__created')
    # ### end Alembic commands ###
