"""empty message

Revision ID: 5f0e26854939
Revises: bab3ad083d37
Create Date: 2018-04-26 08:42:36.110894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0e26854939'
down_revision = 'bab3ad083d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_brand'), 'shop', ['brand'], unique=False)
    op.create_index(op.f('ix_shop_item_name'), 'shop', ['item_name'], unique=False)
    op.create_index(op.f('ix_shop_sex'), 'shop', ['sex'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_colour'), 'stock', ['colour'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_colour'), table_name='stock')
    op.drop_table('stock')
    op.drop_table('order')
    op.drop_index(op.f('ix_shop_sex'), table_name='shop')
    op.drop_index(op.f('ix_shop_item_name'), table_name='shop')
    op.drop_index(op.f('ix_shop_brand'), table_name='shop')
    op.drop_table('shop')
    # ### end Alembic commands ###
