"""empty message

Revision ID: 76c6442afb22
Revises: 5f0e26854939
Create Date: 2018-04-26 11:17:09.276715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c6442afb22'
down_revision = '5f0e26854939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('appointments', sa.Column('time', sa.Time(), nullable=True))
    op.create_index(op.f('ix_appointments_date'), 'appointments', ['date'], unique=False)
    op.create_index(op.f('ix_appointments_time'), 'appointments', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_date'), table_name='appointments')
    op.drop_column('appointments', 'time')
    op.drop_column('appointments', 'date')
    # ### end Alembic commands ###
