"""empty message

Revision ID: a3231da0897b
Revises: 1f81331aa67c
Create Date: 2018-05-05 15:13:42.473837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3231da0897b'
down_revision = '1f81331aa67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    "moo"
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('date', sa.DATE(), nullable=True))
    op.add_column('appointments', sa.Column('time', sa.TIME(), nullable=True))
    op.create_index('ix_appointments_time', 'appointments', ['time'], unique=False)
    op.create_index('ix_appointments_date', 'appointments', ['date'], unique=False)
    # ### end Alembic commands ###
