"""empty message

Revision ID: b6c8385e867c
Revises: 0a379487323b
Create Date: 2018-04-23 09:39:55.595178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c8385e867c'
down_revision = '0a379487323b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'quantity')
    # ### end Alembic commands ###
