"""empty message

Revision ID: bab3ad083d37
Revises: b6c8385e867c
Create Date: 2018-04-25 12:28:55.874269

    """
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab3ad083d37'
down_revision = 'b6c8385e867c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('item_name', sa.String(), nullable=True),
        sa.Column('brand', sa.String(), nullable=True),
        sa.Column('sex', sa.String(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('image', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_brand'), 'shop', ['brand'], unique=False)
    op.create_index(op.f('ix_shop_item_name'), 'shop', ['item_name'], unique=False)
    op.create_index(op.f('ix_shop_sex'), 'shop', ['sex'], unique=False)
    sa.PrimaryKeyConstraint('id')

    op.create_table('stock',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('colour', sa.String(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('item_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['item_id'], ['shop.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_colour'), 'stock', ['colour'], unique=False)
    op.create_table('order',
                    sa.Column("id", sa.Integer(), nullable=False),
                    sa.Column("user_id", sa.Integer, nullable=True),
                    sa.Coloumn("shop_id", sa.Integer, nullable=True),
                    sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
                    sa.ForeignKeyConstraint(["item_id"], ["shop.id"]),
                    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade():
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('shop', sa.Column('colour', sa.VARCHAR(), nullable=True))
        op.add_column('shop', sa.Column('quantity', sa.INTEGER(), nullable=True))
        op.create_index('ix_shop_colour', 'shop', ['colour'], unique=False)
        op.drop_index(op.f('ix_stock_colour'), table_name='stock')
        op.drop_table('stock')
        # ### end Alembic commands ###
