"""empty message

Revision ID: c4637a56df40
Revises: 0f576399b7fd
Create Date: 2018-04-17 17:05:53.173958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4637a56df40'
down_revision = '0f576399b7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_brand'), 'shop', ['brand'], unique=False)
    op.create_index(op.f('ix_shop_item_name'), 'shop', ['item_name'], unique=False)
    op.create_index(op.f('ix_shop_sex'), 'shop', ['sex'], unique=False)
    sa.PrimaryKeyConstraint('id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_date_time'), table_name='appointments')
    op.create_index('ix_appointments_date_time', 'appointments', ['date_time'], unique=False)
    op.drop_table('order')
    op.drop_index(op.f('ix_shop_sex'), table_name='shop')
    op.drop_index(op.f('ix_shop_item_name'), table_name='shop')
    op.drop_index(op.f('ix_shop_colour'), table_name='shop')
    op.drop_index(op.f('ix_shop_brand'), table_name='shop')
    op.drop_table('shop')
    # ### end Alembic commands ###
